ALTER TABLE rooms
ADD COLUMN electricity_price DECIMAL(12,2) DEFAULT NULL,
ADD COLUMN water_price DECIMAL(12,2) DEFAULT NULL,
ADD COLUMN wifi_price DECIMAL(12,2) DEFAULT NULL,
ADD COLUMN parking_price DECIMAL(12,2) DEFAULT NULL,
ADD COLUMN service_price DECIMAL(12,2) DEFAULT NULL;
